# Generated by Django 3.1.5 on 2021-01-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='number',
            new_name='elsaf',
        ),
        migrations.AddField(
            model_name='elsaf',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
