# Generated by Django 3.1.5 on 2021-01-26 06:12

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210125_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=''),
            preserve_default=False,
        ),
    ]
